#!/usr/bin/expect -f
#
#--------------------------------------------------+
#                                                  |
#    Author: Kristoffer Paulsson                   |
#    Email: kristoffer.paulsson@gmail.com          |
#    Copyright: (c) 2015 Kristoffer Paulsson       |
#    License: MIT                                  |
#                                                  |
#--------------------------------------------------+
#


set timeout -1
spawn sudo tasksel install lamp-server
match_max 100000

expect "New password for the MySQL \"root\" user:"
sleep 1
send -- "vagrant\r"

expect "Repeat password for the MySQL \"root\" user:"
sleep 1
send -- "vagrant\r"

expect eof
